[package]
name = "datafusion_ext"
version = "0.1.0"
edition = "2021"

[lib]
name = "datafusion_ext"
crate-type = ["cdylib"]

[dependencies]
arrow = "50.1.0"
blake2 = "0.10"
datafusion = "50.1.0"
datafusion-common = "50.1.0"
datafusion-expr = "50.1.0"
datafusion-python = "50.1.0"
hex = "0.4"
pyo3 = { version = "0.23", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
