[package]
name = "datafusion_ext_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "datafusion_ext_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module"] }
datafusion-python = { path = "../datafusion_python" }
